baseURL = "https://berfilsafat.site/"
languageCode = "en-us"
title = "Berfilsafat | Sebuah informasi untuk anak muda"
theme = "yinyang"
DefaultContentLanguage = "filsafat"



[author]
  name = "Hajid Al Akhtar"
  homepage = "https://hajid.tech/"

staticDir = "static"

[languages]
  [languages.filsafat]
    contentDir = "content/filsafat"
    languageName = "English"
    weight = 1
    
  [languages.cognitive_bias]
    contentDir = "content/cognitive_bias"
    languageName = "English"
    weight = 2

  [languages.page]
    contentDir = "content/page"
    languageName = "English"
    weight = 3


[params]
mainSections = ["posts"]
headTitle = "BERFILSAFAT"
disqus = "hajid_alakhtar" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
[[params.socials]]
name = "About Me"
link = "https://joway.io"
[[params.socials]]
name = "Github"
link = "https://github.com/joway"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []
